### ISSUE TITLE
Please upgrade to rxjs 6

### ISSUE THREAD

**Issue by bdocrex** [tiangolo/ngx-http-client#2]
Using this package causes bulid failures when using rxjs 6 without rxjs-compat.
Please update the code to use rxjs 6 so that rxjs-compat is not required, thanks.

**Comment by misaizdaleka** [comment]
+1

**Comment by tiangolo** [comment]
I'm sorry, I never got to do any more updates to this.

This project was made as a "quick workaround" while waiting for the Angular team to merge the small PR fixing the issue.

I'm no longer using Angular, so I don't really have a way to come back to this. :disappointed: 

As I don't have a way to come back to this and update it, I'm gonna close this issue now.

If you are needing this, the best would be to write a comment in that PR, add a code review approving it, etc. Try to get the attention of the Angular team to accept that PR.

Check more details in the notice: https://github.com/tiangolo/ngx-http-client#notice

You might also consider other options. For example, I that once hated React with JSX, am having a really good time with it now that it has TypeScript support and hooks, editor support is currently great, with completion everywhere, etc.
